---
## ---------------------------------------------------------------
#                           Check install
## ---------------------------------------------------------------

- name: Install python-docker
  package: 
    name: python-docker  

## ---------------------------------------------------------------
#                           Clean
## ---------------------------------------------------------------

- name: clean up volumes that are not used
  shell: "docker volume ls '{{ '{{' }} .Names {{ '}}' }}'" # nasty, docker uses curly brackets too!
  register: currently_present
  changed_when: False

- debug: var=currently_present
  when: playbook_debug

- name: determine which volume to be present
  set_fact:
    should_be_present: "{{ docker_volumes | map(attribute='name') | list | unique }}"

- debug: var=should_be_present
  when: playbook_debug

- name: determine what instance will get removed
  set_fact:
    should_be_removed: "{{ currently_present.stdout_lines | difference(should_be_present) }}"

- debug: var=should_be_removed
  when: playbook_debug

- name: remove unwanted volumes
  docker_volume:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ should_be_removed }}"
  when: enable_remove_unwanted_volumes

## ---------------------------------------------------------------
#                           Create
## ---------------------------------------------------------------

- name: volumes creation
  docker_volume:
    name: "{{ docker_volume.name }}"
    labels: "{{ docker_volume.labels | default(omit) }}"
    state: "{{ docker_volume.state | default(omit) }}"
    force: "{{ docker_volume.force | default(omit) }}"
  loop_control:
    loop_var: docker_volume
  with_items:
    - "{{ docker_volumes }}"

## ---------------------------------------------------------------
#                           Check & Report
## ---------------------------------------------------------------

- name: check container status
  command: docker volume ls
  register: result

- debug: var=result.stdout

- name: Debug de chaque volume
  shell: docker volume inspect {{ docker_volume.name }}
  register: debug_result
  loop_control:
    loop_var: docker_volume
  with_items:
    - "{{ docker_volumes }}"

- debug: var=debug_result.results
  when: playbook_debug
